In [ ]:
BÀI TẬP:
BT1: 1. Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8], tạo array arr_c
chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b.
2. Từ arr_a và arr_b ở câu 1 => Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a.
3. Cho arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]), hãy tạo arr_f chỉ chứa các phần tử
có giá trị từ 5 đến 10 của arr_e. 

In [3]:
import numpy as np
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
#tạo array arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b. 
arr_c = np.intersect1d(arr_a, arr_b)
#Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a. 
arr_d = np.setdiff1d(arr_a, arr_b)
#phần tử trong arr_e có giá trị từ 5 đến 10
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]


print("arr_c:", arr_c)
print("arr_d:", arr_d)
print("arr_f:", arr_f)


arr_c: [2 4]
arr_d: [1 3 5 6]
arr_f: [ 6  9 10  8  6]


In [ ]:
BT2: Hãy hoàn tất file đính kèm với các yêu cầu sau:
1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.
2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_1 từ arr_k với các phần tử khác 0.
4. Từ arr_1 của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [6]:
import numpy as np
# 1) Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 (1-based) là 1
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1

# 2) Tạo arr_h có giá trị từ 10 đến 24, in danh sách các phần tử theo thứ tự đảo ngược
arr_h = np.arange(10, 25)  # 10..24 inclusive
arr_h_reversed = arr_h[::-1]

# 3) Cho arr_k, tạo arr_1 gồm các phần tử khác 0
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_1 = arr_k[arr_k != 0]

# 4) Từ arr_1, thêm 2 phần tử 10 và 20 vào cuối array
arr_after_append = np.append(arr_1, [10, 20])

# 5) Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5 (0-based)
arr_after_insert = np.insert(arr_after_append, 5, 100)

# 6) Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2
arr_after_delete = np.delete(arr_after_insert, [0, 1, 2])

# In kết quả từng bước
print("1) arr_zeros:", arr_zeros)
print("2) arr_h:", arr_h)
print("   arr_h_reversed:", arr_h_reversed)
print("3) arr_k:", arr_k)
print("   arr_1 (khong co zero):", arr_1)
print("4) after append [10,20]:", arr_after_append)
print("5) after insert 100 at index 5:", arr_after_insert)
print("6) after delete indices [0,1,2]:", arr_after_delete)


1) arr_zeros: [0 0 0 0 1 0 0 0 0 0]
2) arr_h: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
   arr_h_reversed: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
3) arr_k: [1 2 0 8 2 0 1 3 0 5 0]
   arr_1 (khong co zero): [1 2 8 2 1 3 5]
4) after append [10,20]: [ 1  2  8  2  1  3  5 10 20]
5) after insert 100 at index 5: [  1   2   8   2   1 100   3   5  10  20]
6) after delete indices [0,1,2]: [  2   1 100   3   5  10  20]


BT3: Hãy hoàn tất file đính kèm với các yêu cầu sau:
1. Tạo array arr có kích thước 3x3 với các giá trị True
2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.
3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.
4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.
5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.
6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), Kiểm tra trong array có giá trị rỗng không?
7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.

In [ ]:
#1 Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True)
print("\n", arr)

'


 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#2Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\n", arr_2D)


 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
#3 Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.
arr_2D[[0, 1]] = arr_2D[[1, 0]]
print("\n", arr_2D)


 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [ ]:
# 4. Đảo ngược các dòng
arr_2D = arr_2D[::-1]
print("\n", arr_2D)


 [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [ ]:
#5. Đảo ngược các cột
arr_2D = arr_2D[:, ::-1]
print("\n", arr_2D)


 [[6 7 8]
 [0 1 2]
 [3 4 5]]


In [ ]:
#6. Kiểm tra giá trị rỗng trong mảng
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_null = np.isnan(arr_2D_null).any()
print("Có giá trị rỗng không?", has_null)

Có giá trị rỗng không? True


In [ ]:
#7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\n", arr_2D_null)


 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
