In [1]:
#4.3 Cac Vi Du 
import numpy as np 
#tao mang mot chieu 
array_1 = np.array([1,2,3])
print(array_1)
print(type(array_1))

[1 2 3]
<class 'numpy.ndarray'>


In [1]:
import numpy as np 
x = [1,2,3] 
a = np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x = (1,2,3 )
a = np.asarray(x) 
print(a)


[1 2 3]
<class 'numpy.ndarray'>


In [8]:
mang_2 = np.arange(10,20,2 )
print(mang_2) 

[10 12 14 16 18]


In [9]:
mang_3 = np.linspace(10, 20, 5)
print(mang_3)
mang_4 = np.linspace(10,20,5, endpoint = False )
print(mang_4)

[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]


In [11]:
#Số phần tử của mảng 
print(a)
print(a.shape[0])

[1 2 3]
3


In [18]:
#cap nhat so phan tu trong mang 
a[1] = 250 
print(a)

[  1 250   3]


In [21]:
# Truy xuất phần tử trong mảng
mang_4 = np.array([1, 3, 2, 4, 5, 7, 9])
print(mang_4)
print(mang_4[3])
print(mang_4[3:])
print(mang_4[3:5])
print(mang_4[mang_4 < 5]) # có kèm điều kiện

[1 3 2 4 5 7 9]
4
[4 5 7 9]
[4 5]
[1 3 2 4]


In [24]:
# Thêm các phần tử vào cuối mảng
mang_5 = np.arange(10)
mang_5 = np.append(mang_5, [25, 30])
print(mang_5)

[ 0  1  2  3  4  5  6  7  8  9 25 30]


In [ ]:
#chen phan tu vao trong index  gia tri 100 
print(mang_5)
mang_5 = np.insert(mang_5,3,100 )
print(mang_5)


[ 0  1  2  3  4  5  6  7  8  9 25 30]
[  0   1   2 100   3   4   5   6   7   8   9  25  30]


In [26]:
print(mang_5)
mang_5 = np.delete(mang_5,11 )
print(mang_5)

[  0   1   2 100   3   4   5   6   7   8   9  25  30]
[  0   1   2 100   3   4   5   6   7   8   9  30]


In [28]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8]) 
mang_cong = a + b
print(mang_cong)
mang_tru = a - b
print(mang_tru)
mang_nhan = a*b
print(mang_nhan)
mang_chia = a / b
print(mang_chia)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [29]:
d = np.array([3, 10, 9, 12, 8, 5])
print(np.amax(d))
print(np.amin(d))

12
3


In [ ]:
#Tính tổng giá trị: sử dụng sum() 
arr = np.arange(10) 
arr.sum()


np.int64(45)

In [ ]:
#Giá trị trung bình số học: sử dụng mean() 
print(d) 
print(np.mean(d))

[ 3 10  9 12  8  5]
7.833333333333333


In [36]:
print(d)
print(np.median(d))

[ 3 10  9 12  8  5]
8.5


In [ ]:
#su dung sort de sap xep mang 
mang_5 = np.array([3,1,2,4,7,8,9,5,6])
print(mang_5)
print(np.sort(mang_5))

[3 1 2 4 7 8 9 5 6]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#Tìm index của các phần tử trong mảng thỏa điều kiện: sử dụng where() 
print(mang_5)
idexes = np.where(mang_5 >= 5)
print(idexes)
print(mang_5[idexes])

[3 1 2 4 7 8 9 5 6]
(array([4, 5, 6, 7, 8]),)
[7 8 9 5 6]


In [44]:
print(mang_5)
print(np.extract(np.mod(mang_5 , 2 )== 0,mang_5 ))
print(np.extract(mang_5 >=  5 , mang_5 )) 


[3 1 2 4 7 8 9 5 6]
[2 4 8 6]
[7 8 9 5 6]
