In [1]:
#Từ object có định dạng array: sử dụng array() 
import numpy as np 
array_2 = np.array([[1,2,3], [4,5,6]])
print(array_2)
print(type(array_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
# tạo mảng với 0 hoặc 1
mang_zeros = np.zeros([2,2,2], dtype = int)
print("Mảng zeros")
print(mang_zeros)
print("Mảng ones")
mang_ones = np.ones([2,2], dtype = int)
print(mang_ones)

Mảng zeros
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
Mảng ones
[[1 1]
 [1 1]]


In [5]:
#4.2.2
#Số dòng, cột trên mảng 
print(array_2) 
print(array_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
#Cập nhật phần tử trong mảng 

array_2[0][0] = 100 
print(array_2)

[[100   2   3]
 [  4   5   6]]


In [7]:
# Truy xuất phần tử trên mảng: theo ma trận, dòng, cột (index = 0 -> chiều dài - 1) 
print(array_2)
print(array_2[1][2])
print(array_2[1],)

[[100   2   3]
 [  4   5   6]]
6
[4 5 6]


In [12]:
#thay doi kich thuoc mang 
print(array_2)
print(array_2.shape )
array_2.shape = (3,2 )
print(array_2)

[[100   2]
 [  3   4]
 [  5   6]]
(3, 2)
[[100   2]
 [  3   4]
 [  5   6]]


In [13]:
#thay doi kich thuoc mang dung reshape 
a= np.arange(24) 
print(a) 
b = a.reshape(2,3,4)
print(b)
print(b[0][1][2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
6


In [15]:
#Tìm max, min: sử dụng amax(), amin()
print("Max:", np.amax(a))
print("Min:", np.amin(a))
print("Max - theo từng cột:", np.amax(a, 0))
print("Min theo từng cột:", np.amin(a, 0))
# Không thể dùng axis=1 cho mảng 1 chiều

Max: 23
Min: 0
Max - theo từng cột: 23
Min theo từng cột: 0


In [17]:
#Giá trị trung bình số học: sử dụng mean()
b = np.array([[[3,7], [8,4]], [[2,4], [1, 5]]])
print(b)
print('Mean b:')
print(np.mean(b))
print('Mean b[0]:')
print(np.mean(b[0]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Mean b:
4.25
Mean b[0]:
5.5


In [18]:
#Giá trị trung bình giữa: sử dụng median() dựa trên mảng đã sắp xếp, lấy trung bình phần tử ở giữa mảng
print(b)
print('Median b:')
print(np.median(b))
print('Median b[1]:')
print(np.median(b[1]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Median b:
4.0
Median b[1]:
3.0


In [19]:
#Sắp xếp tăng dần trong mảng: sử dụng sort() 
c = np.array([[[9,7], [8,4]], [[2,4], [6, 5]]])
print(c)
print("Sort c")
print(np.sort(c))

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Sort c
[[[7 9]
  [4 8]]

 [[2 4]
  [5 6]]]


In [20]:
print('Sort c[0] axis 1 (theo dòng):')
print(np.sort(c[0], axis = 1))

Sort c[0] axis 1 (theo dòng):
[[7 9]
 [4 8]]


In [21]:
print('Sort c[0] axis 0 (theo cột):')
print(np.sort(c[0], axis = 0))

Sort c[0] axis 0 (theo cột):
[[8 4]
 [9 7]]


In [22]:
#Tìm index của các phần tử trong mảng thỏa điều kiện: sử dụng where() 
print(c)
cond = np.where(c>5)
print(cond)
print(c[cond])

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
(array([0, 0, 0, 1]), array([0, 0, 1, 1]), array([0, 1, 0, 0]))
[9 7 8 6]


In [23]:
#Tìm các phần tử trong mảng thỏa điều kiện: sử dụng extract(điều kiện, mảng)
print(c)
print("Trên c:", np.extract (c >= 5, c) )
print("Trên c[0]:", np.extract (c[0] >= 5, c[0]))

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Trên c: [9 7 8 6 5]
Trên c[0]: [9 7 8]
